issues:
  exclude-use-default: true
  exclude:
    - don't use an underscore in package name

linters:
  enable:
      - goimports
      - goconst
      - gosec
      - govet
      - ineffassign
      - revive
      - typecheck
      - unused

linters-settings:
  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    # Default: ""
    local-prefixes: tgbot
