// Code generated by MockGen. DO NOT EDIT.
// Source: add_use_case.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "tgbot/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockDatabase) Add(title models.Title) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", title)
}

// Add indicates an expected call of Add.
func (mr *MockDatabaseMockRecorder) Add(title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockDatabase)(nil).Add), title)
}
